// <auto-generated />
using System;
using BloodBankSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonationSystem.Migrations
{
    [DbContext(typeof(BloodContext))]
    [Migration("20251104103034_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodBankSystem.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BloodBankId")
                        .HasColumnType("int");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.HasIndex("DonorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodBankId = 1,
                            DonorId = 1,
                            Remarks = "First-time donor",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodBankId = 2,
                            DonorId = 2,
                            Remarks = "Follow-up donation",
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BloodBanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            ContactNumber = "9876543210",
                            Email = "che@gmail.com",
                            Location = "Chennai",
                            ManagedBy = "Admin",
                            Name = "Chennai Central Blood Bank"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 400,
                            ContactNumber = "9998877665",
                            Email = "cbe@gmail.com",
                            Location = "Coimbatore",
                            ManagedBy = "Admin",
                            Name = "Coimbatore Blood Bank"
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroupNeeded")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("BloodRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodGroupNeeded = "A+",
                            Quantity = 2,
                            RecipientId = 1,
                            RequestDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            BloodGroupNeeded = "B+",
                            Quantity = 3,
                            RecipientId = 2,
                            RequestDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodBankId")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitsAvailable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.ToTable("BloodStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodBankId = 1,
                            BloodGroup = "A+",
                            LastUpdated = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 2,
                            BloodBankId = 1,
                            BloodGroup = "B+",
                            LastUpdated = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UnitsAvailable = 8
                        },
                        new
                        {
                            Id = 3,
                            BloodBankId = 2,
                            BloodGroup = "O+",
                            LastUpdated = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UnitsAvailable = 12
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodBankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BloodBankId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonationRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodBankId = 1,
                            DonationDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 1,
                            Quantity = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            BloodBankId = 2,
                            DonationDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 2,
                            Quantity = 1,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("EligibilityStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DonorProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 28,
                            BloodGroup = "A+",
                            EligibilityStatus = true,
                            Gender = "Male",
                            LastDonationDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            BloodGroup = "B+",
                            EligibilityStatus = true,
                            Gender = "Male",
                            LastDonationDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonorRequestLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("RequestId");

                    b.ToTable("DonorRequestLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonorId = 1,
                            LinkedAt = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            DonorId = 2,
                            LinkedAt = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestId = 2
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Message = "Your blood request is being processed",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Message = "Your donation appointment is confirmed",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.RecipientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredBloodGroup")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RecipientProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "9876543210",
                            HospitalName = "Apollo Hospital",
                            PatientName = "Priya Devi",
                            RequiredBloodGroup = "A+",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "9998877665",
                            HospitalName = "Global Hospital",
                            PatientName = "Kavya Raj",
                            RequiredBloodGroup = "B+",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "System",
                            LastName = "Admin",
                            PasswordHash = "admin123",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arun@gmail.com",
                            FirstName = "Arun",
                            LastName = "Kumar",
                            PasswordHash = "pass123",
                            Role = 1,
                            Username = "arun"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "suresh@gmail.com",
                            FirstName = "Suresh",
                            LastName = "Rajan",
                            PasswordHash = "pass123",
                            Role = 1,
                            Username = "suresh"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya@gmail.com",
                            FirstName = "Priya",
                            LastName = "Devi",
                            PasswordHash = "pass456",
                            Role = 2,
                            Username = "priya"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kavya@gmail.com",
                            FirstName = "Kavya",
                            LastName = "Raj",
                            PasswordHash = "pass456",
                            Role = 2,
                            Username = "kavya"
                        });
                });

            modelBuilder.Entity("BloodBankSystem.Models.Appointment", b =>
                {
                    b.HasOne("BloodBankSystem.Models.BloodBank", "BloodBank")
                        .WithMany("Appointments")
                        .HasForeignKey("BloodBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BloodBankSystem.Models.DonorProfile", "Donor")
                        .WithMany("Appointments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BloodBank");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodRequest", b =>
                {
                    b.HasOne("BloodBankSystem.Models.RecipientProfile", "Recipient")
                        .WithMany("BloodRequests")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodStock", b =>
                {
                    b.HasOne("BloodBankSystem.Models.BloodBank", "BloodBank")
                        .WithMany("BloodStocks")
                        .HasForeignKey("BloodBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBank");
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonationRecord", b =>
                {
                    b.HasOne("BloodBankSystem.Models.BloodBank", "BloodBank")
                        .WithMany("DonationRecords")
                        .HasForeignKey("BloodBankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BloodBankSystem.Models.DonorProfile", "Donor")
                        .WithMany("DonationRecords")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BloodBank");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonorProfile", b =>
                {
                    b.HasOne("BloodBankSystem.Models.User", "User")
                        .WithOne("DonorProfile")
                        .HasForeignKey("BloodBankSystem.Models.DonorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonorRequestLink", b =>
                {
                    b.HasOne("BloodBankSystem.Models.DonorProfile", "Donor")
                        .WithMany("DonorRequestLinks")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BloodBankSystem.Models.BloodRequest", "Request")
                        .WithMany("DonorRequestLinks")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BloodBankSystem.Models.NotificationLog", b =>
                {
                    b.HasOne("BloodBankSystem.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodBankSystem.Models.RecipientProfile", b =>
                {
                    b.HasOne("BloodBankSystem.Models.User", "User")
                        .WithOne("RecipientProfile")
                        .HasForeignKey("BloodBankSystem.Models.RecipientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodBank", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BloodStocks");

                    b.Navigation("DonationRecords");
                });

            modelBuilder.Entity("BloodBankSystem.Models.BloodRequest", b =>
                {
                    b.Navigation("DonorRequestLinks");
                });

            modelBuilder.Entity("BloodBankSystem.Models.DonorProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DonationRecords");

                    b.Navigation("DonorRequestLinks");
                });

            modelBuilder.Entity("BloodBankSystem.Models.RecipientProfile", b =>
                {
                    b.Navigation("BloodRequests");
                });

            modelBuilder.Entity("BloodBankSystem.Models.User", b =>
                {
                    b.Navigation("DonorProfile");

                    b.Navigation("Notifications");

                    b.Navigation("RecipientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
